// <auto-generated />
using System;
using BirFikrimVar.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BirFikrimVar.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509145354_SeedKategoriler")]
    partial class SeedKategoriler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Degerlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeklenenFaydaPuani")
                        .HasColumnType("integer");

                    b.Property<string>("DegerlendiriciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DegerlendirmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EkNot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FikirId")
                        .HasColumnType("integer");

                    b.Property<int>("KaynakIhtiyaciPuani")
                        .HasColumnType("integer");

                    b.Property<int>("RiskVeSurdurulebilirlikPuani")
                        .HasColumnType("integer");

                    b.Property<int>("StratejikUyumPuani")
                        .HasColumnType("integer");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.Property<int>("UygulanabilirlikPuani")
                        .HasColumnType("integer");

                    b.Property<int>("YenilikcilikPuani")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DegerlendiriciId");

                    b.HasIndex("FikirId");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Fikir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasvuruSahibiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Firsatlar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GucluYonler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kapsam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ozet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tehditler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YenilikciYan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZayifYonler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BasvuruSahibiId");

                    b.ToTable("Fikirler");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.FikirDosyasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint");

                    b.Property<int>("FikirId")
                        .HasColumnType("integer");

                    b.Property<string>("KayitliDosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrijinalDosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Uzanti")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FikirId");

                    b.ToTable("FikirDosyalari");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Stratejik Uyum",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Yenilikçilik",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Uygulanabilirlik",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Beklenen Fayda",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Risk ve Sürdürülebilirlik",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Kaynak İhtiyacı",
                            AktifMi = true
                        });
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.KomisyonDegerlendirmesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DegerlendiriciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DegerlendirmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FikirId")
                        .HasColumnType("integer");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FikirId");

                    b.ToTable("KomisyonDegerlendirmeleri");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.OnOnayDegerlendirmesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DegerlendiriciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DegerlendirmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FikirId")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FikirId");

                    b.HasIndex("KategoriId");

                    b.ToTable("OnOnayDegerlendirmeleri");
                });

            modelBuilder.Entity("FikirDurumGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EskiDurum")
                        .HasColumnType("integer");

                    b.Property<int>("FikirId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IslemYapanKullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YeniDurum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FikirId");

                    b.HasIndex("IslemYapanKullaniciId");

                    b.ToTable("FikirDurumGecmisleri");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("KullaniciRolleri", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Degerlendirme", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", "Degerlendirici")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("DegerlendiriciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BirFikrimVar.Core.Entities.Fikir", "Fikir")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("FikirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degerlendirici");

                    b.Navigation("Fikir");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Fikir", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", "BasvuruSahibi")
                        .WithMany("Fikirler")
                        .HasForeignKey("BasvuruSahibiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasvuruSahibi");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.FikirDosyasi", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Fikir", "Fikir")
                        .WithMany("FikirDosyalari")
                        .HasForeignKey("FikirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fikir");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.KomisyonDegerlendirmesi", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Fikir", "Fikir")
                        .WithMany()
                        .HasForeignKey("FikirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fikir");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.OnOnayDegerlendirmesi", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Fikir", "Fikir")
                        .WithMany()
                        .HasForeignKey("FikirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirFikrimVar.Core.Entities.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fikir");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("FikirDurumGecmisi", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Fikir", "Fikir")
                        .WithMany("DurumGecmisleri")
                        .HasForeignKey("FikirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", "IslemYapanKullanici")
                        .WithMany()
                        .HasForeignKey("IslemYapanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fikir");

                    b.Navigation("IslemYapanKullanici");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BirFikrimVar.Core.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Fikir", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("DurumGecmisleri");

                    b.Navigation("FikirDosyalari");
                });

            modelBuilder.Entity("BirFikrimVar.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Fikirler");
                });
#pragma warning restore 612, 618
        }
    }
}
